apiVersion: v1
kind: Service
metadata:
  name: mongo-server
<<<<<<< HEAD
  namespace: emontoya
=======
  namespace: <namespace>
>>>>>>> master
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongo-server
  type: NodePort