apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-server
spec:
  replicas: 1
  selector:
    app: mongo-server
  template:
    metadata:
      name: mongo-server
      labels:
        app: mongo-server
    spec:
      containers:
      - name: mongo
        image: mongo:3.6.3-jessie
        ports:
        - name: redis-port
          containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        # - name: mongo-configdb
        #   mountPath: /data/configdb
      # volumes:
      # - name: mongo-data
      #   nfs:
      #     server: nas.dis.eafit.edu.co
      #     path: /mnt/NASVOL1/kubernetes/volumes/
      #     readOnly: false
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data
      # - name: mongo-configdb
      #   persistentVolumeClaim:
      #     claimName: mongo-configdb